### PR TITLE
Cawemo to Web Modeler Migration with go script

### PR DESCRIPTION
**Pull request by jonathanlukas**
# Camunda Community Hub Pull Request Template

## Description

The current implementation of the migration script has some weaknesses. The go script does overcome them (or at least some).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an existing open issue)
- [ ] New feature (non-breaking change which adds functionality to an extension)
- [ ] Breaking change (fix or feature that would cause existing functionality of an extension to change)
- [ ] Documentation update (changes made to an existing piece of documentation)

## Checklist:

- [ ] My code adheres to the syntax used by this extension.
- [ ] My pull request requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **Camunda Community Hub** documentation.
- [ ] I have read the **Pull Request Process** documentation.
- [ ] I have added or suggested tests to cover my changes suggested in this pull request.
- [ ] All new and existing CI/CD tests passed.
- [ ] I will /assign myself this issue, and add the relevant [issue labels] to it if they are not automatically generated by Probot.
- [ ] I will tag @camunda-community-hub/devrel in a new comment on this issue if 30 days have passed since my pull request was opened and I have not received a response from the extension's maintainer.

### CODE REVIEW

**Comment by shaarmann** [comment]
Some initial observations:
- It would be great if the scipt can be used for migrating to Webmodeler Self-Managed
- It would be great if the script can assign the projects to a default admins, because the Super-User mode does not exist in self-managed (use the `/collaborators` endpoint)

**Review by shaarmann — CHANGES_REQUESTED** [review]
Hi @jonathanlukas,
I added an update to the README, can you please review the update?

Furthermore, I've some minor remarks:
- Migration of DMN models fails (the other scripts include a [workaround](https://github.com/camunda-community-hub/camunda-7-to-8-migration/blob/main/cawemo-to-web-modeler-migration/migrate-cawemo-to-web-modeler.ps1#L111))
- I'd prefer some error handling. Currently an error causes the whole script to exit and migration stops.
- Logging can improve to also include human readable information (names of folders and files) especially in case of an error.

**Comment by jonathanlukas** [comment]
@shaarmann thank you for the review.

* Migration of DMN model is fixed
* the error behaviour is intended as of now. The script produces a migration state and can therefore be called again. However, I see that some bad things could happen. My plan is that an error will interrupt migration for one file, the rest will continue.
* you are right, logging should be improved. Will happen

**Comment by jonathanlukas** [comment]
@shaarmann there has been more logging added

**Review by shaarmann — APPROVED** [review]
Hi @jonathanlukas,
Thanks for the changes. Looks good to me.
I still don't like the error handling as the only possibility to resolve the error is by removing the model from Cawemo. Yet, I'll approve the request for now, as you said better error handling is something to be implemented in the future.

**Pull request merged**
